name: chat_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.0.1
  cached_network_image: ^3.3.1
  image_picker: ^1.1.2
  file_picker: ^5.2.2
  firebase_storage: ^12.1.0
  intl: ^0.17.0
  rive: ^0.9.0
  emoji_picker_flutter: ^2.2.0
  path: ^1.9.0
  path_provider: ^2.1.3
  firebase_messaging: ^15.0.2               

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - Images/
