// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions Fare not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyBqfOdrcABc_fgJHuntoO_zKr79fpBZM',
    appId: '1:5683487624:web:a1edc66e6fe7127cc5d03d',
    messagingSenderId: '5683487624',
    projectId: 'a-talk-ecb52',
    authDomain: 'a-talk-ecb52.firebaseapp.com',
    storageBucket: 'a-talk-ecb52.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK0XpAM-3bmUwmJnecN6_a7_IByu-jyio',
    appId: '1:5683487624:android:48e718772623de58c5d03d',
    messagingSenderId: '5683487624',
    projectId: 'a-talk-ecb52',
    storageBucket: 'a-talk-ecb52.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyBqfOdrcABc_fgJHuntoO_zKr79fpBZM',
    appId: '1:5683487624:web:8d6886c138a03bcec5d03d',
    messagingSenderId: '5683487624',
    projectId: 'a-talk-ecb52',
    authDomain: 'a-talk-ecb52.firebaseapp.com',
    storageBucket: 'a-talk-ecb52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAClPnurUP-pdvXJ0xXkFKIbmWho8A-agw',
    appId: '1:5683487624:ios:5701cfd30e9cba75c5d03d',
    messagingSenderId: '5683487624',
    projectId: 'a-talk-ecb52',
    storageBucket: 'a-talk-ecb52.appspot.com',
    androidClientId: '5683487624-c7daffa0jrjm0bcslv5brrp1lcjg5v8t.apps.googleusercontent.com',
    iosClientId: '5683487624-n7eurh351djvvt8kp6qfjd2lh1pmtlfc.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

}